# sample-workflow-ubuntu-latest
# docs are in the repo

name: .NET Code Analysis ubuntu-latest
on:
  push:
    branches:
      - main

jobs:
  sample:
    name: .NET Code Analysis runner

    # .NET Code Analysis runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: ubuntu-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Ensure a compatible version of dotnet is installed.
    # A version greater than or equal to v5.0.x of dotnet must be installed on the agent in order to run this action.
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

      # Run open source static analysis tools
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
