# sample-workflow-ubuntu-latest
# docs are in the repo

name: .NET Code Analysis ubuntu-latest
on:
  push:
    branches:
      - main

jobs:
  sample:
    name: .NET Code Analysis runner

    # .NET Code Analysis runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: ubuntu-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Ensure compatible versions of dotnet are installed.
    # The [Microsoft Security Code Analysis CLI](https://aka.ms/mscadocs) is built with dotnet v3.1.201.
    # A version greater than or equal to v3.1.201 of dotnet must be installed on the agent in order to run this action.
    # Remote agents already have a compatible version of dotnet installed and this step may be skipped.
    # For local agents, ensure dotnet version 3.1.201 or later is installed by including this action:
    # - uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '3.1.x'

    # Run NuGet restore for each project/solution to analyze
    - name: Run NuGet restore
      run: dotnet restore <%path_to_project_or_solution%>

    # Run code analysis for all projects/solutions
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        projects: <%semi_colon_separated_paths_to_projects_or_solutions%>
        analysis-level: <%analysis_level%>
